version: '3.3'
services:
  db:
    image: postgres:latest  # Using the latest version of PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: 'db'  # Default database
      POSTGRES_USER: 'user'  # You can use whatever username you like
      POSTGRES_PASSWORD: 'password'  # You can use whatever password you like
    ports:
      # <Port exposed> : <PostgreSQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data  # Where our data will be persisted
# Names our volume
volumes:
  my-db:
